"""Natural question families assigned before expansion: train, validation, test."""
FORMS = {
    'located_in': (['Where is {s}?', 'Where can I find {s}?', 'Which room is {s} in?'], 'What room contains {s}?', 'Where would I go to find {s}?'),
    'location': (['Where is {s}?', 'Where can I find {s}?', 'What is the location of {s}?'], 'Where is {s} situated?', 'At what place is {s} based?'),
    'owner': (['Who owns {s}?', 'Who is responsible for {s}?', 'Who looks after {s}?'], 'Who has responsibility for {s}?', 'Whose responsibility is {s}?'),
    'director': (['Who runs {s}?', 'Who leads {s}?', 'Who is in charge of {s}?'], 'Who oversees {s}?', 'Who is the person directing {s}?'),
    'led_by': (['Who leads {s}?', 'Who heads {s}?', 'Who is the lead for {s}?'], 'Who oversees {s}?', 'Who is the person leading {s}?'),
    'quantity': (['How many {s} are there?', 'How many units of {s} do we have?', 'What is the stock count for {s}?'], 'What quantity of {s} is on hand?', 'How much {s} is currently in stock?'),
    'member_of': (['Which team does {s} belong to?', 'What team is {s} on?', 'Which team includes {s}?'], 'What is the team membership of {s}?', 'Which team counts {s} as a member?'),
    'role': (['What does {s} do?', 'What job does {s} have?', 'What is the job title of {s}?'], 'What role does {s} perform?', 'In what capacity does {s} work here?'),
    'radio_channel': (['What radio channel does {s} use?', 'Which channel can I reach {s} on?', 'What is the radio channel for {s}?'], 'Which radio channel is assigned to {s}?', 'To contact {s}, which radio channel should I use?'),
    'shift': (['When is {s} on duty?', 'What hours does {s} work?', 'When is the shift for {s}?'], 'During which hours is {s} on shift?', 'What working hours are recorded for {s}?'),
    'opens_at': (['When does {s} open?', 'What time does {s} open?', 'What is the opening time of {s}?'], 'At which time does {s} open?', 'When do opening hours begin for {s}?'),
    'status': (['Is {s} operational?', 'What condition is {s} in?', 'What is the current status of {s}?'], 'What status does the log give {s}?', 'How is the operational state of {s} recorded?'),
    'serial_number': (['What is the serial number of {s}?', 'Which serial number belongs to {s}?', 'What serial is on {s}?'], 'What serial identifier is assigned to {s}?', 'Which serial identifier identifies {s}?'),
    'inspection_day': (['When is {s} inspected?', 'What day is inspection for {s}?', 'On which day do we inspect {s}?'], 'Which day is assigned for inspecting {s}?', 'What weekday is the inspection of {s}?'),
    'floor': (['What floor is {s} on?', 'Which floor contains {s}?', 'On what floor can I find {s}?'], 'Which floor number belongs to {s}?', 'What building floor houses {s}?'),
    'capacity': (['How many people fit in {s}?', 'What is the capacity of {s}?', 'How many people can {s} hold?'], 'What occupancy capacity is recorded for {s}?', 'What number of people can occupy {s}?'),
    'reorder_threshold': (['When should {s} be reordered?', 'What is the reorder threshold for {s}?', 'What stock level triggers reordering {s}?'], 'At what threshold is {s} due for reorder?', 'What is the minimum stock level before reordering {s}?'),
    'unit': (['What units are used for {s}?', 'How is {s} counted?', 'What is the unit for {s}?'], 'Which measurement unit is recorded for {s}?', 'In what units is the stock of {s} measured?'),
    'access': (['How do I access {s}?', 'What do I need to enter {s}?', 'What access is required for {s}?'], 'What entry requirement applies to {s}?', 'What credential is needed to enter {s}?'),
    'call_sign': (['What is the call sign of {s}?', 'What callsign does {s} use?', 'How is {s} identified on radio?'], 'Which callsign is assigned to {s}?', 'What radio callsign identifies {s}?'),
    'purpose': (['What is {s} for?', 'What is the purpose of {s}?', 'What does {s} research?'], 'What purpose is recorded for {s}?', 'What is the stated mission of {s}?'),
    'focus': (['What does {s} study?', 'What is the research focus of {s}?', 'What does {s} focus on?'], 'What research area is assigned to {s}?', 'What is the stated research specialty of {s}?'),
}
